Send script messages to STDERR.
Thanks Joerg Schiermeier.

diff --git a/debian/scripts/wine b/debian/scripts/wine
--- a/debian/scripts/wine
+++ b/debian/scripts/wine
@@ -12,12 +12,12 @@ elif test -x $wine64; then
     wine=$wine64
     if [ "$(dpkg --print-architecture)" = "amd64" -a "$(dpkg --print-foreign-architectures | grep -cx "i386")" -ne 1 ] ||
        [ "$WINEARCH" = "win32" ]; then
-        echo "it looks like multiarch needs to be enabled.  as root, please"
-        echo "execute \"dpkg --add-architecture i386 && apt-get update &&"
-        echo "apt-get install $(echo $name | sed s/wine/wine32/)\""
+        echo "it looks like multiarch needs to be enabled.  as root, please" >&2
+        echo "execute \"dpkg --add-architecture i386 && apt-get update &&" >&2
+        echo "apt-get install $(echo $name | sed s/wine/wine32/)\"" >&2
     fi
 else
-    echo "error: unable to find wine executable.  this shouldn't happen."
+    echo "error: unable to find wine executable.  this shouldn't happen." >&2
     exit 1
 fi
 
diff --git a/debian/scripts/wineserver b/debian/scripts/wineserver
--- a/debian/scripts/wineserver
+++ b/debian/scripts/wineserver
@@ -11,7 +11,7 @@ if test -x "$wineserver64"; then
 elif test -x "$wineserver32"; then
     wineserver=$wineserver32
 else
-    echo "error: unable to find wineserver executable.  this shouldn't happen."
+    echo "error: unable to find wineserver executable.  this shouldn't happen." >&2
     exit 1
 fi
 
@@ -19,8 +19,8 @@ dist=$(cat /etc/debian_version)
 arch=$(dpkg --print-architecture)
 version=$($wineserver --version 2>&1 | cut -d- -f2)
 
-echo "Executing $name ($(basename $wineserver)) $version on Debian $dist ($arch)."
-echo "If something goes wrong, please rerun with \"WINEDEBUG=err+all $name\""
-echo "for more detailed debugging output."
+echo "Executing $name ($(basename $wineserver)) $version on Debian $dist ($arch)." >&2
+echo "If something goes wrong, please rerun with \"WINEDEBUG=err+all $name\"" >&2
+echo "for more detailed debugging output." >&2
 
 exec $wineserver -p0 "$@"
