If wine32 is missing warn about it unless err output is disabled.
Closes: #818874

Don't show the warning if WINEDEBUG is set to not show errors
(err-all or -all).
Display the multiarch instructions only if needed.

This merges the commits from master:

9e6573170821325e5212c89612f023205f7a0e0c
 If wine32 is missing warn about it unless err output is disabled.
3c733ad57b848262b76486efc6606093db87de21
 Fix wording of the wine32 hint.
cf1d8ebd65503dde7d29094e1cc807ec795adc64
 Simplify WINEDEBUG test in wine script.

diff --git a/debian/scripts/wine b/debian/scripts/wine
--- a/debian/scripts/wine
+++ b/debian/scripts/wine
@@ -6,6 +6,17 @@ bindir=/usr/lib/$script
 wine32=$bindir/wine
 wine64=$bindir/wine64
 
+wine32_hint () {
+    echo "it looks like $(echo $script | sed s/wine/wine32/) is missing, you should install it."
+    if [ "$(dpkg --print-architecture)" = "amd64" -a "$(dpkg --print-foreign-architectures | grep -cx "i386")" -ne 1 ]; then
+        echo "multiarch needs to be enabled first.  as root, please"
+        echo "execute \"dpkg --add-architecture i386 && apt-get update &&"
+        echo "apt-get install $(echo $script | sed s/wine/wine32/)\""
+    else
+        echo "as root, please execute \"apt-get install $(echo $script | sed s/wine/wine32/)\""
+    fi
+}
+
 if test -x $wine32; then
     wine=$wine32
 elif test -x $wine64; then
@@ -13,12 +24,13 @@ elif test -x $wine64; then
     if test -z "$WINELOADER"; then
         export WINELOADER=$wine64
     fi
-    if [ "$(dpkg --print-architecture)" = "amd64" -a "$(dpkg --print-foreign-architectures | grep -cx "i386")" -ne 1 ] ||
-       [ "$WINEARCH" = "win32" ]; then
-        echo "it looks like multiarch needs to be enabled.  as root, please" >&2
-        echo "execute \"dpkg --add-architecture i386 && apt-get update &&" >&2
-        echo "apt-get install $(echo $script | sed s/wine/wine32/)\"" >&2
-    fi
+    case "x$WINEDEBUG" in
+        x-all*|x*,-all*|x*err-all*)
+            ;;
+        *)
+            wine32_hint >&2
+            ;;
+    esac
 else
     echo "error: unable to find wine executable.  this shouldn't happen." >&2
     exit 1
